name: Roadmap Sync

on:
  push:
    branches:
      - main
    paths:
      - 'roadmap.md'
  schedule:
    - cron: '0 0 1 * *' # Monthly token rotation

jobs:
  sync:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
      
      - name: Install dependencies
        run: npm ci
      
      - name: Configure Git
        run: |
          git config --global credential.helper store
          echo "https://${{ secrets.GH_PAT }}@github.com" > ~/.git-credentials
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
      
      - name: MCP Sync
        env:
          GH_PAT: ${{ secrets.GH_PAT }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: roadmap-sync --auto
      
      - name: Rotate PAT (Monthly)
        if: github.event_name == 'schedule'
        env:
          GH_PAT: ${{ secrets.GH_PAT }}
          GH_PAT_ROTATION_KEY: ${{ secrets.GH_PAT_ROTATION_KEY }}
        run: |
          npm install -g @octokit/rest
          node scripts/rotate-pat.js